In [1]:
import numpy as np

In [4]:


# create a one-dimensional ndarray containing 36 ones
ones_36 = np.ones(36)
print(ones_36)

# reshape as a 6 x 6, two-dimensional array
ones_6x6 = np.reshape(ones_36, (6, 6))
print(ones_6x6)

# # reshape as a 2 x 3 x ? three-dimensional array
ones_3d = ones_36.reshape(2, 3, 6)
print(ones_3d)

# # what was the third shape dimension for ones_3d?
ones_3d_third_shape_value = 6
print(ones_3d_third_shape_value)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[[[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1.]]]
6


In [9]:
# Create an 8x8 array containing numbers from 1 to 64 and assign this array to array_64_8x8.
# Assign its transpose to transposed_array_64_8x8.

numbers = [i for i in range(1,65)]
a = np.array(numbers).reshape((8,8))

print(a)

b = a.transpose()
print(b)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]
[[ 1  9 17 25 33 41 49 57]
 [ 2 10 18 26 34 42 50 58]
 [ 3 11 19 27 35 43 51 59]
 [ 4 12 20 28 36 44 52 60]
 [ 5 13 21 29 37 45 53 61]
 [ 6 14 22 30 38 46 54 62]
 [ 7 15 23 31 39 47 55 63]
 [ 8 16 24 32 40 48 56 64]]
