In [13]:
import numpy as np
import pandas as pd

In [2]:
a = np.array([5,3,2])
b = np.array([1,1,1])

In [4]:
c = 2*b + a
c

array([7, 5, 4])

In [5]:
x = np.array([1,2,3,4,5,6,7])

c = (x > 2) & (x <=6)
c

array([False, False,  True,  True,  True,  True, False])

In [12]:
arr = np.array([[3, 4, 5], [6, 7, 8]])

arr.max(axis=1)


array([5, 8])

In [22]:
df1 = pd.DataFrame([[1,2], [3,4]], columns=['a','b'])
df1.columns(['colA', 'colB'])
df1

TypeError: 'Index' object is not callable

In [19]:
df1['c'] = df1['a'] + df1['b']
df1

a  b  c
0  1  2  3
1  3  4  7