In [1]:
import numpy as np

In [8]:
# be sure to do your import
import numpy as np


# import the contents of grades.csv
grades_array = np.loadtxt("grades.csv", delimiter=",", dtype=str)

print(grades_array)

[['Student' ' Math' ' English' ' Gym']
 ['Sanjay' ' 83' ' 87' ' 84']
 ['Sally' ' 93' ' 97' ' 94']
 ['Edgar' ' 73' ' 77' ' 74']]


In [9]:
# a slice containing only the grades
# as a float datatype
only_grades = grades_array[1:, 1:].astype(np.float)

print(only_grades)

[[83. 87. 84.]
 [93. 97. 94.]
 [73. 77. 74.]]


/var/folders/hr/by8v61fn78d0t79dw472nz6w0000gn/T/ipykernel_26896/3254342008.py:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  only_grades = grades_array[1:, 1:].astype(np.float)


In [11]:
# the mean for all students across all classes
overall_grades_mean = only_grades.mean()

print(f"Overall grades mean: {overall_grades_mean}")

Overall grades mean: 84.66666666666667


In [12]:
# student means
student_mean = only_grades.mean(axis=1)

sanjay_mean = student_mean[0]
sally_mean = student_mean[1]
edgar_mean = student_mean[2]

print(f"Sanja mean: {sanjay_mean}")
print(f"Sally mean: {sally_mean}")
print(f"Edgar mean: {edgar_mean}")

Sanja mean: 84.66666666666667
Sally mean: 94.66666666666667
Edgar mean: 74.66666666666667


In [13]:
# grade means
grade_mean = only_grades.mean(axis=0)

gym_mean = grade_mean[2]
math_mean = grade_mean[0]
english_mean = grade_mean[1]

print(f"Gym mean: {gym_mean}")
print(f"Math mean: {math_mean}")
print(f"English mean: {english_mean}")

Gym mean: 84.0
Math mean: 83.0
English mean: 87.0
